### PR TITLE
[Feature] Automatic download. Thanks @NirmalScaria

### PR DESCRIPTION
**Pull request by ramazansancar**
This pull request resolves #

 - [X] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [X] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [X] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [X] I have tested all of my changes.
 
Source: https://github.com/NirmalScaria/movie-web-extension/commit/cda573acd5060eab62f304e20bcebe0f368f6455
Repo: https://github.com/NirmalScaria/movie-web-extension
Thanks @NirmalScaria

### CODE REVIEW

**Comment by ramazansancar** [comment]
Check pls @NoelJacob

**Comment by NoelJacob** [comment]
Can you send PR to upstream repo at Gittea. I'll update this with upstream asap. This is only a mirror for that upstream repo.

**Comment by ramazansancar** [comment]
I have no idea how to do it. Can you help me? @NoelJacob

**Comment by ramazansancar** [comment]
Thanks for Merge PR 🙌 @NoelJacob

**Comment by NoelJacob** [comment]
Sorry for being really late

**Pull request merged**
